# Generated by Django 5.2.3 on 2025-06-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('vintage', models.PositiveIntegerField(blank=True, null=True)),
                ('grape_varieties', models.CharField(blank=True, max_length=255, null=True)),
                ('wine_type', models.CharField(blank=True, choices=[('red', 'Red'), ('white', 'White'), ('rosé', 'Rosé'), ('sparkling', 'Sparkling')], max_length=50, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
