# Generated by Django 5.2.3 on 2026-01-01 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winemanager', '0002_stores_bottle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='quantity',
        ),
    ]
