# Generated by Django 5.2.3 on 2026-01-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winemanager', '0003_remove_bottle_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='consumed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
