# Generated by Django 5.2.3 on 2026-01-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winemanager', '0004_bottle_consumed_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stores',
            new_name='Store',
        ),
    ]
