# Generated by Django 5.2.3 on 2026-01-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winemanager', '0005_rename_stores_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Rating from 0.0 to 5.0', max_digits=2, null=True),
        ),
    ]
