# Generated by Django 5.2.3 on 2026-01-10 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winemanager', '0006_wine_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wines/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Rating from 0.0 to 5.0', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
