# Generated by Django 5.2.3 on 2026-02-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("winemanager", "0008_alter_wine_country_alter_wine_wine_type_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="alcohol_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Alcohol percentage (e.g. 13.5)",
                max_digits=4,
                null=True,
            ),
        ),
    ]
